version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'America/Santiago'
    container_name: Inventory
    # user: "1000:1000"
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data